# Configuración local - NO COMMITEAR
# Este archivo contiene credenciales locales

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/streamvault
    username: postgres
    password: Junos123
  datasource:
    url: jdbc:postgresql://localhost:5432/streamvault
    username: postgres
    password: Junos123
