# Configuración local - NO COMMITEAR
# Este archivo contiene credenciales locales sensibles

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streamvault
    username: postgres
    password: Junos123

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin